server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esta línea es la magia que hace que el router de Vue funcione correctamente
        try_files $uri $uri/ /index.html;
    }

    # Configuración opcional para mejorar caché de archivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        root /usr/share/nginx/html;
        expires max;
        log_not_found off;
    }
}